name: dlnd
channels:
- brown-data-science
- conda-forge
- defaults
dependencies:
- leptonica=1.74.1=0
- libgcc=5.4.0=0
- openjpeg=2.1.2=0
- tesseract=3.05.01=0
- appnope=0.1.0=py27_0
- asn1crypto=0.22.0=py27_0
- backports=1.0=py27_1
- backports.functools_lru_cache=1.4=py27_1
- backports.shutil_get_terminal_size=1.0.0=py_3
- backports.weakref=1.0rc1=py27_1
- backports_abc=0.5=py27_0
- bkcharts=0.2=py27_0
- blas=1.1=openblas
- bleach=1.5.0=py27_0
- bokeh=0.12.9=py27_0
- bzip2=1.0.6=1
- certifi=2017.7.27.1=py27_0
- cffi=1.10.0=py27_0
- chardet=3.0.4=py27_0
- configparser=3.5.0=py27_0
- cryptography=2.0.3=py27_0
- cycler=0.10.0=py27_0
- dask-core=0.15.3=py_0
- decorator=4.1.2=py27_0
- entrypoints=0.2.3=py27_1
- enum34=1.1.6=py27_1
- ffmpeg=3.2.4=1
- funcsigs=1.0.2=py_2
- functools32=3.2.3.2=py27_1
- futures=3.1.1=py27_0
- gettext=0.19.8.1=0
- giflib=5.1.4=0
- glib=2.51.4=0
- hdf5=1.8.18=1
- html5lib=0.9999999=py27_0
- icu=58.1=1
- idna=2.6=py27_1
- imageio=2.2.0=py27_0
- ipaddress=1.0.18=py27_0
- ipykernel=4.6.1=py27_0
- ipython=5.5.0=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=7.0.1=py_2
- jasper=1.900.1=1
- jedi=0.10.2=py27_0
- jinja2=2.9.6=py27_0
- jsonschema=2.6.0=py27_0
- jupyter=1.0.0=py27_0
- jupyter_client=5.1.0=py27_0
- jupyter_console=5.1.0=py27_0
- jupyter_core=4.3.0=py27_0
- libffi=3.2.1=3
- libgfortran=3.0.0=0
- libiconv=1.14=4
- libsodium=1.0.10=0
- libwebp=0.5.2=7
- libxml2=2.9.5=0
- markdown=2.6.9=py27_0
- markupsafe=1.0=py27_0
- mistune=0.7.4=py27_0
- mock=2.0.0=py27_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py27_0
- networkx=2.0=py27_0
- notebook=5.1.0=py27_0
- numpy=1.11.3=py27_blas_openblas_202
- olefile=0.44=py27_0
- openblas=0.2.19=2
- opencv=2.4.12=np111py27_1
- pandas=0.20.3=py27_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py27_0
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- pbr=3.1.1=py27_0
- pcre=8.39=0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pillow=3.2.0=py27_0
- pip=9.0.1=py27_0
- pixman=0.34.0=0
- prompt_toolkit=1.0.15=py27_0
- protobuf=3.4.0=py27_0
- ptyprocess=0.5.2=py27_0
- pycparser=2.18=py27_0
- pygments=2.2.0=py27_0
- pyopenssl=17.2.0=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=4.11.4=py27_2
- pysocks=1.6.7=py27_0
- python=2.7.13=1
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- pywavelets=0.5.2=np111py27_0
- pyyaml=3.12=py27_1
- pyzmq=16.0.2=py27_2
- qtconsole=4.3.1=py27_0
- requests=2.18.4=py27_1
- scandir=1.6=py27_0
- scikit-image=0.13.0=py27_2
- scikit-learn=0.19.0=py27_blas_openblas_201
- scipy=0.19.1=py27_blas_openblas_202
- setuptools=36.3.0=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_1
- six=1.11.0=py27_1
- ssl_match_hostname=3.5.0.1=py27_1
- tensorflow=1.3.0=py27_0
- terminado=0.6=py27_0
- testpath=0.3.1=py27_0
- toolz=0.8.2=py_2
- tornado=4.5.2=py27_0
- tqdm=4.18.0=py_0
- traitlets=4.3.2=py27_0
- urllib3=1.22=py27_0
- wcwidth=0.1.7=py27_0
- webencodings=0.5=py27_0
- werkzeug=0.12.2=py_1
- wheel=0.30.0=py_1
- widgetsnbextension=3.0.3=py27_2
- x264=20131217=3
- zeromq=4.2.1=1
- cairo=1.14.8=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- harfbuzz=0.9.39=2
- jbig=2.1=0
- jpeg=8d=2
- libpng=1.6.27=0
- libprotobuf=3.2.0=0
- libtiff=4.0.6=2
- matplotlib=1.5.1=np111py27_0
- mkl=2017.0.3=0
- openssl=1.0.2l=0
- qt=4.8.7=4
- readline=6.2=2
- sqlite=3.13.0=0
- tk=8.5.18=0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.5
  - backports.functools-lru-cache==1.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - dask==0.15.3
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15

